"""Integration tests for the streaming conversation pipeline.

    ConversationManager -> tokens out, `conversation:sentence_ready` on the bus

This is the most-used path in the product and it has been effectively uncovered
since M4. Two separate staleness problems stacked on top of each other:

1. `FakeLLM.stream_response` was `(prompt, model)` while the real client had
   grown `system_prompt`, so every test here failed at argument binding with an
   error nobody read. Fixed by `tests/llm_doubles.py` plus a contract test.

2. Underneath that, this module was written against a `ConversationManager`
   that took a `VoiceManager` and yielded `audio` events directly
   (`v0.5.4B-streaming-conversation`). Sprint Alpha.6 replaced that with the
   event bus: the manager takes an `event_bus`, emits sentences onto it, and
   the Speech runtime decides whether to speak. Roughly half of these tests
   asserted `type == "audio"` from the manager and could never have passed
   again — fixing the double alone just moved the failure one layer down.

So the audio-pipeline assertions are gone from here rather than repaired. They
belong to the voice stack (`voice/tests/`, `runtimes/speech/`), which is out of
scope for the alpha and skipped on a base install. What remains is what
`ConversationManager` actually promises today, which is the part the product
depends on.
"""

from __future__ import annotations

import asyncio

from core.event_bus import EventBus
from services.conversation_manager import ConversationManager
from tests.llm_doubles import FakeLLM


def _types(events: list[dict]) -> list[str]:
    return [e.get("type") for e in events]


def _sentences(bus: EventBus) -> list[str]:
    """Sentences the manager published, in order."""
    return [
        e.data["text"]
        for e in bus.get_history(limit=1000)
        if e.event_type == "conversation:sentence_ready"
    ]


# --- completion / no hang -------------------------------------------------- #
def test_conversation_streams_tokens_and_terminates():
    bus = EventBus()
    cm = ConversationManager(FakeLLM(), bus)

    events = list(cm.run_conversation("hi", "gemma3:latest", "default"))

    assert events[-1] == {"type": "done"}, "must terminate with a 'done' event"
    assert "token" in _types(events)
    assert "error" not in _types(events)


def test_tokens_arrive_in_the_order_the_engine_produced_them():
    bus = EventBus()
    cm = ConversationManager(FakeLLM(tokens=["a", "b", "c", "d."]), bus)

    events = list(cm.run_conversation("hi", "gemma3:latest", "default"))
    tokens = [e["content"] for e in events if e.get("type") == "token"]

    assert tokens == ["a", "b", "c", "d."], (
        "the manager hands tokens between two threads through a queue; "
        "reordering here would reorder the reply the user reads"
    )


def test_done_is_last_and_appears_once():
    bus = EventBus()
    cm = ConversationManager(FakeLLM(), bus)

    events = list(cm.run_conversation("hi", "gemma3:latest", "default"))

    assert _types(events).count("done") == 1
    assert _types(events)[-1] == "done"


# --- what actually reaches the engine -------------------------------------- #
def test_the_model_and_system_prompt_reach_the_engine():
    """M4's bug, held down by a test.

    `/chat` accepted a model, the dispatcher logged it on the line above the
    call that did not pass it, and the engine always used its own default. A
    double that ignores its arguments cannot catch that, which is why
    `FakeLLM` records them.
    """
    bus = EventBus()
    llm = FakeLLM()
    cm = ConversationManager(llm, bus)

    list(cm.run_conversation("write a proposal", "qwen2.5:7b", "You are terse."))

    assert llm.calls == [("write a proposal", "You are terse.", "qwen2.5:7b")]


def test_an_empty_system_prompt_is_still_passed_positionally():
    """Guards the argument *order*, which no type checker can see through.

    `stream_response(prompt, system_prompt, model)` and the old
    `(prompt, model, system_prompt)` both accept three strings happily. Swapped,
    the model name arrives as the system prompt and the reply is generated by
    the default model under instructions that read "gemma3:latest".
    """
    bus = EventBus()
    llm = FakeLLM()
    cm = ConversationManager(llm, bus)

    list(cm.run_conversation("hi", "gemma3:latest"))

    (_, system_prompt, model) = llm.calls[0]
    assert model == "gemma3:latest"
    assert system_prompt == ""


# --- sentence segmentation onto the bus ------------------------------------ #
def test_sentences_are_published_to_the_bus():
    bus = EventBus()
    cm = ConversationManager(FakeLLM(), bus)

    list(cm.run_conversation("hi", "gemma3:latest", "default"))

    sentences = _sentences(bus)
    assert sentences, "the Speech runtime has nothing to subscribe to"
    assert all(s.strip() for s in sentences), "blank sentences must not be published"


def test_a_trailing_fragment_is_flushed_not_dropped():
    """A reply that does not end in punctuation still reaches the bus.

    The planner buffers until a sentence boundary, so without the explicit
    flush the last fragment of every unpunctuated reply would be silently lost.
    """
    bus = EventBus()
    cm = ConversationManager(FakeLLM(tokens=["no", " terminator", " here"]), bus)

    list(cm.run_conversation("hi", "gemma3:latest", "default"))

    assert "".join(_sentences(bus)).strip() == "no terminator here"


def test_the_persona_travels_with_the_sentence():
    bus = EventBus()
    cm = ConversationManager(FakeLLM(), bus)

    list(cm.run_conversation("hi", "gemma3:latest", "default", persona="zaram_calm"))

    published = [e for e in bus.get_history(limit=1000) if e.event_type == "conversation:sentence_ready"]
    assert published
    assert all(e.data["persona"] == "zaram_calm" for e in published)


# --- failure paths --------------------------------------------------------- #
def test_an_engine_failure_becomes_an_error_event_and_still_terminates():
    class ExplodingLLM:
        def stream_response(self, prompt, system_prompt="", model=None):
            yield "partial"
            raise RuntimeError("engine exploded")

    bus = EventBus()
    cm = ConversationManager(ExplodingLLM(), bus)

    events = list(cm.run_conversation("hi", "gemma3:latest", "default"))

    assert "error" in _types(events)
    assert events[-1] == {"type": "done"}, "a failure must not leave the stream open"


def test_a_subscriber_that_raises_does_not_break_the_reply():
    """The bus is not a trust boundary the conversation should depend on.

    A speech runtime that throws must not cost the user their text.
    """
    bus = EventBus()

    def boom(event):
        raise RuntimeError("subscriber exploded")

    bus.subscribe("conversation:sentence_ready", boom)
    cm = ConversationManager(FakeLLM(), bus)

    events = list(cm.run_conversation("hi", "gemma3:latest", "default"))

    assert "token" in _types(events)
    assert events[-1] == {"type": "done"}


def test_an_engine_that_yields_nothing_still_terminates():
    bus = EventBus()
    cm = ConversationManager(FakeLLM(tokens=[]), bus)

    events = list(cm.run_conversation("hi", "gemma3:latest", "default"))

    assert events == [{"type": "done"}]


# --- cancellation / no hanging generators --------------------------------- #
async def test_cancellation_mid_stream_terminates_cleanly():
    bus = EventBus()
    cm = ConversationManager(FakeLLM(), bus)

    gen = cm.run_conversation("hi", "gemma3:latest", "default")
    seen = [next(gen) for _ in range(2)]
    assert "token" in _types(seen)

    gen.close()  # must not hang and must not raise

    # Give the worker thread a chance to exit; a hang shows up as a timeout.
    await asyncio.sleep(0.2)


async def test_cancellation_before_any_event_no_hang():
    bus = EventBus()
    cm = ConversationManager(FakeLLM(), bus)

    gen = cm.run_conversation("hi", "gemma3:latest", "default")
    gen.close()  # cancelled before pulling anything

    await asyncio.sleep(0.2)
