"""The design tokens every generated document shares, in one place.

**Two renderers had two designs, and only one of them was designed.** HTML — the
source of truth, and what WeasyPrint turns into a PDF — carries a considered
stylesheet: A4 with print margins, a serif text face, uppercase letterspaced
section heads, hairline table rules, a teal accent. The Word exporter rebuilt
the same document block by block against `python-docx`'s stock template, so what
landed in Word was Calibri 11pt, headings in Word 2007's `#365F91` blue, 1 inch
by 1.25 inch margins, and "Table Grid" — a box drawn around every cell.

Measured on a generated proposal before this module existed. Nothing was wrong
with the composer; the design simply stopped at the HTML boundary.

So the tokens live here and both renderers read them. Not because sharing
constants is tidy, but because the failure mode is silent: change the accent in
one file and the other keeps the old one, and nobody notices until a client has
both a PDF and a Word copy of the same document.

**Fonts are named twice on purpose.** CSS wants a stack, because the document
is rendered by whatever is installed and the next name down is the safety net.
Word wants **one** name — it stores the name and substitutes silently if it is
absent, so a stack is meaningless there and the honest choice is the face most
likely to be present on the machine that opens the file. Georgia and Segoe UI
ship with Windows and Office; the CSS stacks put Charter and Palatino first
because macOS has them and they are better.
"""

from __future__ import annotations

# --------------------------------------------------------------------------- #
# Colour
# --------------------------------------------------------------------------- #

#: Body text. Not pure black: #000 on white is harsher than any printed book,
#: and the difference is visible on a laser printer as well as on screen.
INK = "14171a"
#: Section labels, table headers, the metadata block — everything a reader scans
#: rather than reads.
MUTED = "5b6570"
#: Rules and table borders. Light enough to organise without drawing attention.
RULE = "d8dde2"
#: The one accent, used for the document kind and nothing else.
#:
#: Teal rather than a blue, and that is deliberate: every stock Office template
#: is blue, so blue is the colour that reads as "generated by a word processor".
ACCENT = "0f766e"

#: Word wants `RRGGBB` and CSS wants `#RRGGBB`. One conversion, here, rather
#: than a `#` that someone eventually forgets in an XML attribute — where it is
#: not an error, it is simply ignored, and the text comes out black.
def css(colour: str) -> str:
    return f"#{colour}"


# --------------------------------------------------------------------------- #
# Type
# --------------------------------------------------------------------------- #

#: Serif for body text, because a document is read in long lines and on paper.
#: Charter and Palatino ship on macOS, Cambria and Georgia on Windows; the last
#: entries keep Linux honest.
SERIF_STACK = (
    "Charter,'Bitstream Charter','Palatino Linotype',Palatino,Cambria,Georgia,serif"
)
#: Sans for labels, table headers and the metadata block.
SANS_STACK = (
    "'Segoe UI',Inter,-apple-system,BlinkMacSystemFont,'Helvetica Neue',Arial,sans-serif"
)

#: What Word is told to use. One name each — see the module docstring.
WORD_SERIF = "Georgia"
WORD_SANS = "Segoe UI"

#: Body size in points, shared by both renderers so a PDF and a .docx of the
#: same document have the same texture.
BODY_PT = 11.0
#: Leading, as a multiple. 1.4 in Word against the CSS 1.65 is the same optical
#: result: Word's line spacing multiplier is applied to a value that already
#: includes the font's internal leading, and 1.65 there is visibly airy.
BODY_LINE = 1.4

#: Section heading (`h2`): small, uppercase, letterspaced. Set in the sans face
#: so it reads as a label rather than as a smaller title.
H2_PT = 9.0
#: Sub-heading (`h3`): the serif again, because it is part of the text.
H3_PT = 11.5
#: The document title.
TITLE_PT = 20.0
#: The sources block, and anything else set small.
SMALL_PT = 9.0

#: Letterspacing for the uppercase labels, in points. Word stores this in
#: twentieths of a point; the conversion lives in `word_theme`.
TRACKING_PT = 0.9


# --------------------------------------------------------------------------- #
# Page
# --------------------------------------------------------------------------- #

#: A4, in millimetres, with a wider foot than head so the text block sits
#: slightly above centre rather than looking like it is sliding off the page.
PAGE_TOP_MM = 22
PAGE_RIGHT_MM = 20
PAGE_BOTTOM_MM = 24
PAGE_LEFT_MM = 20
